[package]
name = "khttp"
version = "0.1.0"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["http", "web", "server", "client", "minimal"]
description = "A low-level 0-dependency synchronous HTTP/1.1 client/server library"
edition = "2021"
license = "MIT"
authors = ["karlivory"]
homepage = "https://github.com/karlivory/khttp"
repository = "https://github.com/karlivory/khttp"
readme = "README.md"

[lib]
name = "khttp"
path = "src/lib.rs"

[features]
default = []
client = []
cli = ["client"]

[[bin]]
name = "khttp"
path = "cli/main.rs"
required-features = ["cli"]
