[package]
name = "khttp"
version = "0.1.0"
edition = "2024"

[lib]
name = "khttp"
path = "src/lib.rs"

[features]
default = []
client = []
cli = ["client"]

[[bin]]
name = "khttp"
path = "cli/main.rs"
required-features = ["cli"]
